[package]
name = "read"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "2"
ron = "0.8"
strum = "0.26"
serde = {version = "1", features  = ["derive"]}
book = {path = "../book"}
bible = {path = "../bible"}
